mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from homepage.views import home_screen_view, profile_page_view
from django.conf import settings
from django.conf.urls.static import static

from account.views import *
from contact.views import contact_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name='home'),
    path('account/', account_view, name="account"),
    path('gallery/', gallery_view, name="gallery"),
    path('teller/', include('teller.urls', 'teller')),
    path('profilepage/', profile_page_view, name='profilepage'),
    path('makepayment/', makepayment_view, name='makepayment'),
    path('dashboard/', dashboard_view, name='dashboard'),

    # path('profilepage/', include('profilepage.urls', 'profilepage')),
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='login'),
    path('contact/', contact_view, name='contact'),
    
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

]


 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teller/urls.py
from django.urls import path
from teller.views import (
   add_teller_view,
   detail_teller_view,
   edit_teller_view,
)

app_name = 'teller'

urlpatterns = [
    path('addteller/', add_teller_view, name="addteller"),
    path('<slug>/', detail_teller_view, name="detailteller"),
    path('<slug>/edit', edit_teller_view, name="editteller"),

]

teller/models.py
from django.db import models
 
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver

def upload_location(instance, filename, **kwargs):
    file_path = 'blog/{author_id}/{title}-{filename}'.format(
            author_id=str(instance.author.id), title=str(instance.title), filename=filename
        )

    return file_path

class TellerPost(models.Model):
    title                   = models.CharField(max_length=50, null=False, blank=False)
    body                    = models.TextField(max_length=5000, null=False, blank=False)
    image                   = models.ImageField(upload_to=upload_location, null=False, blank=False)
    date_published          = models.DateTimeField(auto_now_add=True, verbose_name="date published")
    date_updated            = models.DateTimeField(auto_now=True, verbose_name="date updated")
    author                  = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug                    = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.title

@receiver(post_delete, sender=TellerPost)
def submisson_delete(sender, instance, **kwargs):
    instance.image.delete(False)

def pre_save_teller_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_teller_post_receiver, sender=TellerPost)

teller/forms.py
from django import forms

from teller.models import TellerPost

class CreateTellerForm(forms.ModelForm):

    class Meta:
        model = TellerPost
        fields = ['title', 'body', 'image']


class UpdateTellerPostForm(forms.ModelForm):

    class Meta:
        model = TellerPost
        fields = ['title', 'body', 'image']

    def save(self, commit=True):
        teller_post = self.instance
        teller_post.title = self.cleaned_data['title']
        teller_post.body = self.cleaned_data['body']

        if self.cleaned_data['image']:
            teller_post.image = self.cleaned_data['image']

        if commit:
            _post(save)
        return teller_post

teller/views.py
from django.shortcuts import render, redirect, get_object_or_404

from teller.models import TellerPost
from teller.forms import CreateTellerForm, UpdateTellerPostForm
from account.models import Account

def add_teller_view(request):

    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('login')

    form = CreateTellerForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(email=user.email).first()
        obj.author = author
        obj.save()
        context['success_message'] = 'Teller uploaded successfully'

        form = CreateTellerForm()

    context['form'] = form
    return render(request, 'teller/add_teller.html', {})

def detail_teller_view(request, slug):

    context = {}
    if not request.user.is_authenticated:
        return redirect("login")
    teller_post = get_object_or_404(TellerPost, slug=slug)
    context['teller_post'] = teller_post
    return render(request, 'teller/detail_teller.html', context)

def edit_teller_view(request, slug):
    
    context = {} 

    user = request.user
    if not user.is_authenticated:
        return redirect("login")

    teller_post = get_object_or_404(TellerPost, slug=slug)
    if teller_post.author != user:
        return HttpResponse("You are not allowed to view this page!!") 

    if request.POST:
        form = UpdateTellerPostForm(request.POST or None, request.FILES or None, instance=teller_post)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['success_message'] = 'Updated'
            teller_post = obj

    form = UpdateTellerPostForm(
            initial = {
                    # "title": teller_post.title,
                    "body": teller_post.body,
                    "image": teller_post.image,
            }
    )

    context['form'] = form
    return render(request, 'teller/edit_teller.html', context)

teller/templates/teller/add_teller.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mowarid Hostel | Dashboard</title>
    <link rel="stylesheet" href="../../../static/dist/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="../../../static/css/main2.css">
</head>
<body>
<nav class="navbar bg-blue navbar-inverse navbar-fixed-top">
<div class="container-fluid">
    <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{% url 'logout' %}"> <i class="fa fa-home"></i> Mowarid Hostel</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'dashboard' %}"><i class="fa fa-home"></i> Dashboard</a></li>
              <li><a href="{% url 'account' %}"> <i class="fa fa-user"></i> Account</a></li>
              <li><a href="{% url 'makepayment' %}"><i class="fa fa-credit-card"></i> Make payments</a></li>
              <li><a href="{% url 'teller:addteller' %}"><i class="fa fa-image"></i> Upload Teller</a></li>
              <li><a href="{% url 'logout' %}"><i class="fa fa-power-off"></i> Logout</a></li>
            </ul>
            
          </div>
        </div>
      </nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li><a href="{% url 'dashboard' %}"> <i class="fa fa-home"></i> Dashboard<span class="sr-only">

                <li><a href="{% url 'account' %}"><i class="fa fa-user"></i> Account<span class="sr-only">(current)</a></li>
                <li><a href="{% url 'makepayment' %}"><i class="fa fa-credit-card"></i> Make payments</a></li>
                <li class="active"><a href="{% url 'teller:addteller' %}"><i class="fa fa-image"></i> Upload Teller</a></li>
                <li><a href="{% url 'logout' %}"> <i class="fa fa-power-off"></i> Logout</a></li>
            </ul>
        </div>
    </div>        
</div>
<div class="col-sm-9  col-md-offset-2 main">
    <h1 class="page-header">Welcome, {{user.username}}</h1>
    <!-- <h3>Your Personal Details</h3> -->
  <div class="col-sm-9  col-md-offset-0">
      <style type="text/css">

        .create-form {
      
            width: 100%;
      
            max-width: 100%;
      
            padding: 15px;
      
            margin: auto;
      
          }
      
      
      
          .submit-button{
      
            max-width: 200px;
      
          }
          
          </style>
        
        
      
<div class="container">

  <div class="row">

    <div class="col-lg-7 offset-lg-1">

      {% if success_message %}

      <h3 style="color:green; text-align: center;">{{success_message}}</h3>

    {% endif %}
      <form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

        <!-- title -->
        <div class="form-group">

          <label for="id_title">Title</label>

          <input class="form-control" type="text" name="title" id="id_title" placeholder="{{ user.room_number }}" required autofocus>

        </div>

        <!-- Body -->

        <div class="form-group">

          <label for="id_body">Content</label>

          <textarea class="form-control" rows="8" type="text" name="body" id="id_body" placeholder="Teller number" required></textarea>

        </div>

        <!-- Image -->

        <div class="form-group">

          <label for="id_image">Image</label>

          <input  type="file" name="image" id="id_image" accept="image/*" required>

        </div>

        <!-- Submit btn -->

        <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>

      </form>	

    </div>

  </div>

</div>
        
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="../../../static/js/bootstrap.min.js"></script>
</body>
</html>

teller/templates/teller/detail_teller.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="../../../static/dist/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="../../../static/css/main2.css">
</head>
<body>
<nav class="navbar bg-blue navbar-inverse navbar-fixed-top">
<div class="container-fluid">
    <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{% url 'logout' %}"> <i class="fa fa-home"></i> Mowarid Hostel</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'dashboard' %}"><i class="fa fa-home"></i> Dashboard</a></li>
              <li><a href="{% url 'account' %}"> <i class="fa fa-user"></i> Account</a></li>
              <li><a href="{% url 'makepayment' %}"><i class="fa fa-credit-card"></i> Make payments</a></li>
              <li><a href="{% url 'teller:addteller' %}"><i class="fa fa-image"></i> Upload Teller</a></li>
              <li><a href="{% url 'logout' %}"><i class="fa fa-power-off"></i> Logout</a></li>
            </ul>
            
          </div>
        </div>
      </nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li><a href="{% url 'dashboard' % }"> <i class="fa fa-home"></i> Dashboard</a></li>
                <li><a href="{% url 'account' %}"><i class="fa fa-user"></i> Account<span class="sr-only">(current)</a></li>
                <li><a href="{% url 'makepayment' %}"><i class="fa fa-credit-card"></i> Make payments</a></li>
                <li class="active"><a href="{% url 'teller:addteller' %}"><i class="fa fa-image"></i> Upload Teller</a></li>
                <li><a href="{% url 'logout' %}"> <i class="fa fa-power-off"></i> Logout</a></li>
            </ul>
        </div>
    </div>        
</div>
<div class="col-sm-9  col-md-offset-2 main">
    <h1 class="page-header">Welcome, {{user.username}}</h1>
    <!-- <h3>Your Personal Details</h3> -->
    <div class="col-sm-9  col-md-offset-0">
            <style type="text/css">
                .card{
                    max-width: 700px;
        
                }
        
                .container{
                    padding: 20px;
                }
            </style>
        
        <div class="container">
            <div class="row">
                <div class="card m-auto">
                    <img class="card-img-top" src="{{ teller_post.image.url }}" alt="">
                    <div class="card-body my-2">
                        <h2 class="card-title">{{teller_post.title}}</h2>
                        <p class="card-text">{{teller_post.body}}</p>
                        {% if teller_post.author == request.user %}
                            <a href="{% url 'teller:editteller' teller_post.slug%}" class="btn btn-primary">Edit</a>
                        {% endif %}
                    </div>
                    <div class="card-footer text-muted">
                        Updated on {{teller_post.date_updated}} by {{teller_post.author}}
                    </div>
                </div>
            </div>
        </div>
        
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="../../../static/js/bootstrap.min.js"></script>
</body>
</html>

teller/templates/teller/edit_teller.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="../../../static/dist/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="../../../static/css/main2.css">
</head>
<body>
<nav class="navbar bg-blue navbar-inverse navbar-fixed-top">
<div class="container-fluid">
    <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{% url 'logout' %}"> <i class="fa fa-home"></i> Mowarid Hostel</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'dashboard' %}"><i class="fa fa-home"></i> Dashboard</a></li>
              <li><a href="{% url 'account' %}"> <i class="fa fa-user"></i> Account</a></li>
              <li><a href="{% url 'makepayment' %}"><i class="fa fa-credit-card"></i> Make payments</a></li>
              <li><a href="{% url 'teller:addteller' %}"><i class="fa fa-image"></i> Upload Teller</a></li>
              <li><a href="{% url 'logout' %}"><i class="fa fa-power-off"></i> Logout</a></li>
            </ul>
            
          </div>
        </div>
      </nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li><a href="{% url 'dashboard' % }"> <i class="fa fa-home"></i> Dashboard</a></li>
                <li><a href="{% url 'account' %}"><i class="fa fa-user"></i> Account<span class="sr-only">(current)</a></li>
                <li><a href="{% url 'makepayment' %}"><i class="fa fa-credit-card"></i> Make payments</a></li>
                <li class="active"><a href="{% url 'teller:addteller' %}"><i class="fa fa-image"></i> Upload Teller</a></li>
                <li><a href="{% url 'logout' %}"> <i class="fa fa-power-off"></i> Logout</a></li>
            </ul>
        </div>
    </div>        
</div>
<div class="col-sm-9  col-md-offset-2 main">
    <h1 class="page-header">Welcome, {{user.username}}</h1>
    <!-- <h3>Your Personal Details</h3> -->
    <div class="col-sm-9  col-md-offset-0">
        <style type="text/css">

            .create-form {
         
                 width: 100%;
         
                 max-width: 100%;
         
                 padding: 15px;
         
                 margin: auto;
         
               }
         
         
         
               .submit-button{
         
                   max-width: 200px;
         
               }
         
         
         
             .image {
         
               opacity: 1;
         
               transition: .5s ease;
         
               backface-visibility: hidden;
         
             }
         
         
         
             .middle {
         
               transition: .5s ease;
         
               opacity: 0;
         
               position: absolute;
         
               text-align: center;
         
               top: 50%;
         
               left: 50%;
         
               transform: translate(-50%, -50%);
         
             
         
             }
         
             .image-group{
         
                 position: relative;
         
                   text-align: center;
         
                   cursor:pointer;
         
             }
         
         
         
             .image-group:hover .image {
         
               opacity: 0.3;
         
             }
         
         
         
             .image-group:hover .middle {
         
               opacity: 1;
         
             }
         
         
         
             .text {
         
               margin: auto;
         
               background-color: #4CAF50;
         
               color: white;
         
               font-size: 15px;
         
               padding: 15px;
         
             }
         
         </style>
         
         
         
         <div class="container">
         
             <div class="row">
         
                 <div class="col-lg-7 offset-lg-1">
         
         
         
                     {% if success_message %}
         
                         <h3 style="color:green; text-align: center;">{{success_message}}</h3>
         
                     {% endif %}
         
         
         
                     <form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}
         
         
         
                         <!-- title -->
         
                         <!-- <div class="form-group">
         
                             <label for="id_title">Title</label>
         
                             <input class="form-control" type="text" name="title" id="id_title" placeholder="Title" value="{{form.initial.title}}" required autofocus>
         
                         </div>
          -->
         
         
                         <!-- Body -->
         
                         <div class="form-group">
         
                             <label for="id_body">Content</label>
         
                             <textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." 
         
                             required>{{form.initial.body}}</textarea>
         
                         </div>
         
         
         
                         <!-- Image -->
         
                         <div class="form-group image-group" id="id_image_group">
         
                             <img class="img-fluid image" src="{{form.initial.image.url}}" id="id_image_display">
         
                               <div class="middle">
         
                                 <div class="text">Change image</div>
         
                               </div>
         
                         </div>
         
                         <input type="file" name="image" id="id_image_file" accept="image/*" onchange="readURL(this)">
         
                         
         
         
         
                         {% for field in form %}
         
                             <p>
         
                                 {% for error in field.errors %}
         
                                     <p style="color: red">{{ error }}</p>
         
                                 {% endfor %}
         
                             </p>
         
                         {% endfor %}
         
                         {% if form.non_field_errors %}
         
                             <div style="color: red">
         
                                 <p>{{form.non_field_errors}}</p>
         
                             </div>
         
                         {% endif %}
         
         
         
                         <!-- Submit btn -->
         
                         <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
         
                     </form>	
         
                 </div>
         
             </div>
         
         </div>
         
         
         
         <script type="text/javascript">
         
             document.getElementById('id_image_group').onclick = function(event){
         
                 document.getElementById('id_image_file').click();
         
             };
         
         
         
             function readURL(input){
         
                 var reader = new FileReader();
         
                 reader.onload = function (e) {
         
                     $('#id_image_display')
         
                         .attr('src', e.target.result)
         
                 };
         
                 reader.readAsDataURL(input.files[0]);
         
             }
         
         </script>
         
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="../../../static/js/bootstrap.min.js"></script>
</body>
</html>